name: MacOS X build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: install dependencies
      run: |
        brew install libx11 libxi libxtst

    - name: configure
      run: ./configure

    - name: build
      run: make

    - name: stage install
      run: DESTDIR=spacenavd-instdir make install

    - uses: actions/upload-artifact@v3
      with:
        name: spacenavd-instdir
        path: spacenavd-instdir

# vi:ts=2 sts=2 sw=2 expandtab:
